### ISSUE TITLE
不知名原因运行失败

### ISSUE THREAD

**Issue by kao0312** [kono-dada/VN-ChatGPT-Translator#7]
Microsoft Windows [版本 10.0.22621.1992]
(c) Microsoft Corporation。保留所有权利。

C:\Users\admin>py C:\Users\admin\Desktop\VN-ChatGPT-Translator-main\main.py
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\VN-ChatGPT-Translator-main\main.py", line 1, in <module>
    from translator import Translator
  File "C:\Users\admin\Desktop\VN-ChatGPT-Translator-main\translator.py", line 6, in <module>
    from configs import *
  File "C:\Users\admin\Desktop\VN-ChatGPT-Translator-main\configs.py", line 7, in <module>
    all_text = os.listdir(text_dir)
               ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'text'

C:\Users\admin>cd C:\Users\admin\Desktop\VN-ChatGPT-Translator-main

C:\Users\admin\Desktop\VN-ChatGPT-Translator-main>py C:\Users\admin\Desktop\VN-ChatGPT-Translator-main\main.py
Traceback (most recent call last):
  File "C:\Users\admin\Desktop\VN-ChatGPT-Translator-main\main.py", line 12, in <module>
    account = int(sys.argv[1])
                  ~~~~~~~~^^^
IndexError: list index out of range

C:\Users\admin\Desktop\VN-ChatGPT-Translator-main>

**Comment by Young-Lord** [comment]
你README都没认真看吧…这个py main.py要传两个参数：一个账号ID和一个开始时间
